# grid search options, extensive version
logit:
    penalty: [l1, l2]
    C: [0.01, 0.1, 1.0, 10.0, 100, 1000]

DT:
    criterion: [gini, entropy]
    max_depth: [1, 5, 10, 20, 50, 100]
    max_features: [sqrt, log2]
    min_samples_split: [2, 5, 10]
RF:
    criterion: [gini, entropy]
    n_estimators: [1000]
    max_depth: [20, 50] 
    max_features: [sqrt, log2]
    min_samples_split: [3, 10]
SGD:
    loss: [hinge, log, perceptron]
    penalty: [l2, l1, elasticnet]
ET:
    criterion: [gini, entropy]
    n_estimators: [1000]
    max_depth: [20, 50] 
    max_features: [sqrt, log2]
    min_samples_split: [3, 10]
AB:
    algorithm: [SAMME, SAMME.R]
    n_estimators: [1, 10, 100, 1000, 10000]
GB:
    n_estimators: [1000]
    learning_rate: [0.001, 0.01, 0.05, .1, .5]
    subsample: [0.5, 1]
    max_depth: [1, 3, 10, 20]
SVM:
    C: [0.001, 0.01, 0.1, 1]
    kernel: [linear]
KNN:
    n_neighbors: [1,5,10,25,50]
    weights: [uniform, distance]
    algorithm: [auto, ball_tree, kd_tree]
